{"name": "test_ecommerce_page[chrome]", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.TimeoutException: Message:", "trace": "self = <Tests.Test_NumberInputPage.Test_NumInput object at 0x0000024B31DF7D60>\n\n    @allure.severity(allure.severity_level.NORMAL)\n    def test_ecommerce_page(self):\n        self.inputPage = InputPage(self.driver)\n>       self.inputPage.do_number_check(TestWeb.TestPhoneNumber)\n\nTests\\Test_NumberInputPage.py:53: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\nPages\\NumberInputPage.py:40: in do_number_check\n    self.do_send_keys(self.num_input_field, number)\nPages\\function.py:28: in do_send_keys\n    WebDriverWait(self.driver, 10).until(EC.visibility_of_element_located(by_locator)).send_keys(text)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <selenium.webdriver.support.wait.WebDriverWait (session=\"ccdc955451fa32a3ca0ba9295f638cd9\")>\nmethod = <selenium.webdriver.support.expected_conditions.visibility_of_element_located object at 0x0000024B31DF7040>, message = ''\n\n    def until(self, method, message=''):\n        \"\"\"Calls the method provided with the driver as an argument until the \\\n        return value is not False.\"\"\"\n        screen = None\n        stacktrace = None\n    \n        end_time = time.time() + self._timeout\n        while True:\n            try:\n                value = method(self._driver)\n                if value:\n                    return value\n            except self._ignored_exceptions as exc:\n                screen = getattr(exc, 'screen', None)\n                stacktrace = getattr(exc, 'stacktrace', None)\n            time.sleep(self._poll)\n            if time.time() > end_time:\n                break\n>       raise TimeoutException(message, screen, stacktrace)\nE       selenium.common.exceptions.TimeoutException: Message:\n\nvenv\\lib\\site-packages\\selenium\\webdriver\\support\\wait.py:80: TimeoutException"}, "parameters": [{"name": "init_driver", "value": "'chrome'"}], "start": 1615937779552, "stop": 1615937790866, "uuid": "a0896939-230a-4836-ae8c-76ef0a47c341", "historyId": "959d4f833701f0f8ea1eaeb20b32a989", "testCaseId": "bee397b07ba1d58be0affccca164bd65", "fullName": "Tests.Test_NumberInputPage.Test_NumInput#test_ecommerce_page", "labels": [{"name": "severity", "value": "normal"}, {"name": "tag", "value": "@pytest.mark.usefixtures('init_driver')"}, {"name": "parentSuite", "value": "Tests"}, {"name": "suite", "value": "Test_NumberInputPage"}, {"name": "subSuite", "value": "Test_NumInput"}, {"name": "host", "value": "DESKTOP-C0MQJUT"}, {"name": "thread", "value": "12852-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Tests.Test_NumberInputPage"}]}